### ISSUE TITLE
Beta verison Code Bug,softinpainting and checkpoint name

### ISSUE THREAD

**Issue by pinea00** [DrCyanide/cyanic-sd-krita#42] opened 2024-07-30 03:14 UTC
softinpainting error
** Error running post_sample: S:\stable-diffusion-webui\extensions-builtin\soft-inpainting\scripts\soft_inpainting.pyt]
Traceback (most recent call last):
File "S:\stable-diffusion-webui\modules\scripts.py", line 904, in on_mask_blend
script.on_mask_blend(p, mba, *script_args)
File "S:\stable-diffusion-webui\extensions-builtin\soft-inpainting\scripts\soft_inpainting.py", line 694, in on_mask_blend
get_modified_nmask(settings, mba.nmask, mba.sigma[0]))
File "S:\stable-diffusion-webui\extensions-builtin\soft-inpainting\scripts\soft_inpainting.py", line 124, in get_modified_nmask
return torch.pow(nmask, (sigma ** settings.mask_blend_power) * settings.mask_blend_scale)
TypeError: unsupported operand type(s) for ** or pow(): 'Tensor' and 'dict'
---------------------------------
If there is a '.' in the checkpoint name, the words following it cannot be displayed.

**Comment by DrCyanide** [comment] 2024-07-30 05:14
I just pushed a fix for the checkpoint name issue, see if that fixes it.

For the Soft Inpainting error, it looks like that's an error from the API. Was that in the Stable Diffusion console or was that in a Krita error message? Are you using A1111 or some other backend?

If you can reproduce the error message again, try copying the `log.json` file out of your `cyanic-sd-krita/cyanic` folder and uploading it here. The log has your last call to the Stable Diffusion API in it, so if I can try sending the same call to my backend and see if it also crashes or if it's something wrong with your backend.

**Comment by pinea00** [comment] 2024-07-30 05:50
THanks ,this is log file
[log.json](https://github.com/user-attachments/files/16422616/log.json)

I use this UI(softinpaint is work normally in main code)
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu

**Comment by DrCyanide** [comment] 2024-07-30 16:02
Hum... Are you sure it's not working? These are the images that were in the log, and it seems to match the prompt (going off of translated).

<img width="384" alt="pinea_input" src="https://github.com/user-attachments/assets/b643ed3d-872b-4e7b-9166-c36d95609c8d">
<img width="384" alt="pinea_output" src="https://github.com/user-attachments/assets/f2a23226-c88f-4779-bcc2-4166786d5289">

When I try running it directly on my own server with a different model (not inpainting), I get a valid response too.

<img width="384" alt="pinea_input" src="https://github.com/user-attachments/assets/4932183d-e871-49af-a974-86637cc44c84">

The only thing that confuses me is that there's no sign of a mask in the log, which the plugin should require for Inpainting - which makes me wonder if the log didn't get updated on the last attempt - since that only happens after the request completes. Could you show me what you're doing in Krita so I can try and reproduce it?

**Comment by DrCyanide** [comment] 2024-07-31 01:48
I just pushed a new version to Beta that has some better logging, so it'll record what was sent to the server even if a response doesn't come back.

**Comment by pinea00** [comment] 2024-07-31 05:05
Uploading softError(1).mp4…

I should only switch A1111 and Forge test API, and interleave main and Beta code testing. Although Beta can generate pictures using softinpainting in A1111, the A1111 error message like the title will appear, but the main will not error. In addition, I found that if Beta inpaint If the mask error occurs, the API cannot be used even if you reconnect. You must re-open Krita. If the main code mask error occurs, you can use it as long as you reconnect without closing KRITA.

**Comment by pinea00** [comment] 2024-07-31 05:45
Beta Code inpaint If the mask error occurs, the API cannot be used even if you reconnect. You must re-open Krita
https://youtu.be/VrEpA-drUTA

**Comment by DrCyanide** [comment] 2024-07-31 05:59
![image](https://github.com/user-attachments/assets/e2820344-621f-47e5-98da-636ceb127026)

This error box has the information I need to fix the bug. There's a lot of the error message that's out of view, but I _think_ I pushed a change that will fix it - but it might not hide the mask while generating the image.

Whenever that kind of error window comes up it means a portion of Cyanic SD Krita is **very** broken. In this case it broke while trying to get the data ready to send to Stable Diffusion, and restarting Krita was the only way to restart the plugin.

**Comment by pinea00** [comment] 2024-07-31 11:27
Thank you for your reply. I think I'd better use Main code. Even if scheduler is not entered, the program will automatically direct to the fastest scheduler type.
In addition, removing the background A1111 has moved the model to 'stable-diffusion-webui\models\u2net' instead of the original temporary folder.

**Closed as completed** 2024-11-03 11:45 UTC
