### ISSUE TITLE
controlNet models not showing for forge

### ISSUE THREAD

**Issue by Hellrunner2k** [DrCyanide/cyanic-sd-krita#30] opened 2024-03-22 18:00 UTC
hello... just kicked off auto for forge and i noticed the cNet models are not showing up ... moved the models to the folder ... nothing
halp ^^ 

![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/16692344/1786ad18-9334-42aa-aaac-9d37c2f00da3)
![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/16692344/7a056609-8d66-4611-a504-e395ddc33b27)

and this comes up when i select a preprocessor which are listed

KeyError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Fri Mar 22 18:57:55 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py in <lambda>()
  138         self.preprocessor_select.setMaxVisibleItems(5) # Suppose to limit the number of visible options
  139         # self.preprocessor_select.currentIndexChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText())) # ... This steps through EVERY index in between
  140         self.preprocessor_select.currentTextChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText()))
  141         control_type_row.layout().addRow('Preprocessor', self.preprocessor_select)
  142 
self = <cyanic.extension_widgets.controlnet.ControlNetUnit object>
self.preprocessor_select = <PyQt5.QtWidgets.QComboBox object>
self.preprocessor_select.currentTextChanged = <bound PYQT_SIGNAL currentTextChanged of QComboBox object>
self.preprocessor_select.currentTextChanged.connect = <built-in method connect of PyQt5.QtCore.pyqtBoundSignal object>
self.set_preprocessor_settings = <bound method ControlNetUnit.set_preprocessor_se...ension_widgets.controlnet.ControlNetUnit object>>
self.preprocessor_select.currentText = <built-in method currentText of QComboBox object>

 C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py in set_preprocessor_settings(self=<cyanic.extension_widgets.controlnet.ControlNetUnit object>, preprocessor_name='softedge_pidinet')
  398         self.preprocessor = preprocessor_name
  399 
  400         details = self.cnapi.module_details[preprocessor_name]
  401         self.model_select.setHidden(details['model_free'])
  402 
details undefined
self = <cyanic.extension_widgets.controlnet.ControlNetUnit object>
self.cnapi = <cyanic.extension_widgets.controlnet.ControlNetAPI object>
self.cnapi.module_details = {}
preprocessor_name = 'softedge_pidinet'
KeyError: 'softedge_pidinet'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('softedge_pidinet',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py", line 140, in <lambda>
    self.preprocessor_select.currentTextChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText()))
  File "C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py", line 400, in set_preprocessor_settings
    details = self.cnapi.module_details[preprocessor_name]
KeyError: 'softedge_pidinet'

**Comment by DrCyanide** [comment] 2024-03-22 18:14
I'll have to download Forge myself and test it. It is very odd that the ControlNet list should be empty unless it's not configured right in Forge. The ControlNet API is separate from the WebUI/SD.Next/Forge API, so that part shouldn't be an issue.

While I do that, can you paste the responses to these URLs? That should help me find out what's going on.
localhost:7860/controlnet/version
localhost:7860/controlnet/model_list?update=true
localhost:7860/controlnet/module_list?alias_names=true

**Comment by DrCyanide** [comment] 2024-03-22 18:46
Just got it installed, and while I don't have it set up to use my models yet I already see the problem - those URLs I use to get the ControlNet options are all non-functional, returning `{"detail":"Not Found"}`. This is odd, because the [documentation page](https://github.com/lllyasviel/stable-diffusion-webui-forge/wiki/ControlNet-Web-API) for the Forge ControlNet API seems like it should work, and also uses http://localhost:7860/controlnet/module_list

Because the documentation suggests that these API calls should be the same, my current guess is that this is a Forge Settings issue, and not Krita Plugin issue. I'll keep looking to see if I can find what setting needs to be changed to get it working.

**Comment by DrCyanide** [comment] 2024-03-22 19:32
After a few times starting Forge up again, I got the model_list and module_list APIs to return, but I'm not sure how. I did edit the webui-user.bat file that Forge includes, which allowed it to see my A1111 installed models, hypernetworks, embeddings, and loras (but not my ControlNet). However, I don't think that is what did it, as when I commented those lines out again and restarted Forge it was still working.

As I dug into this, I'm more shocked that you even got ControlNet to show up in Krita at all. The API call that I use to check if ControlNet is installed was deleted from Forge, as were the the APIs to get Models, VAEs, Textual embeddings, and many, many others.

### **Cyanic-SD-Krita will not support Forge**

It looks like they've removed too many of the `/sdapi/v1/` API calls which this plugin was built around for it to be supported. It's possible that there's something odd with the stand-alone version I'm using that's causing APIs to start/stop working randomly, but that only makes me less confident that I can support it.

**Comment by Hellrunner2k** [comment] 2024-03-22 20:04
i STRONGLY suggest that you rethink this approach ^^ .. the trend is moving away from auto... forge is just better.. it's the same but efficient and fast ... no one i know uses auto anymore ... maybe switch to forge native... and talk to the forge dude, maybe ... must be possible to get functionality back if it got thrown out without considering everything.. thank you for your service ... Krita is the future of SD... 
also come to the civitai discord if you like to get an ear to the ground

**Comment by DrCyanide** [comment] 2024-03-22 21:37
I've made a ticket on Forge's issue tracker for it. -
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/599

Here's a list of API calls that Cyanic SD Krita uses which do not seem to be present in Forge (you can check them at http://localhost:7860/docs):
* /sdapi/v1/system-info/status
* /sdapi/v1/progress
* /sdapi/v1/options
* /sdapi/v1/samplers
* /sdapi/v1/upscalers
* /sdapi/v1/sd-models
* /sdapi/v1/face-restorers
* /sdapi/v1/prompt-styles
* /sdapi/v1/sd-vae
* /sdapi/v1/scripts
* /sdapi/v1/embeddings
* /sdapi/v1/hypernetworks
* /sdapi/v1/interrupt
* /sdapi/v1/txt2img
* /sdapi/v1/img2img
* /sdapi/v1/extra-single-image
* /sdapi/v1/interrogate

When the only `/sdapi/v1` endpoints that Forge seems to support are `/sdapi/v1/loras` and `/sdapi/v1/refresh-loras` then the only thing that work in Krita is listing your LoRAs. Looking at the example code in their Read Me, it's pretty clear that Forge was designed around supporting WebUI extensions, not completely separate programs that use the API. Maybe that's an oversight, or maybe it's been intentionally cut for performance improvements. 

If anyone in your Discord server knows their way around the Forge API they're more than welcome to make the necessary changes to my `sdapi_v1.py` and submit a pull request. However I will not be pursuing it further unless I hear back from Forge. 

It doesn't matter how popular Forge or ComfyUI or Fooocus or any other UI is. It matters if they're backwards compatible with the A1111 API. I'm fine making small changes and workarounds like I've done for SD.Next, but I won't be doing ground-up rewrites for other APIs.

**Comment by Hellrunner2k** [comment] 2024-03-23 05:00
fair... I see what i can get

**Comment by DrCyanide** [comment] 2024-03-23 18:57
Looks like Forge is back on the table! Their documentation (plus the FastAPI documentation page loading) made it seem like it *did not* need the `--api` commandline arg and behaved similar to SD.Next (which automatically activates the API). Adding that to my starting args gets an API that Cyanic SD Krita can interact with, and I successfully was able to pick my models and do Txt2Img tests.

Back to the initial problem, the ControlNet API is still a bit different than the A1111 and SD.Next versions. It doesn't have `/controlnet/settings` (which let me check how many ControlNet Units there are), nor does it have `/controlnet/control_types` (which tells which Models + Preprocessors go with which tab, like Canny or OpenPose). 

I tried checking `/sdapi/v1/options` to see if the Units have been moved there, but I'm not seeing it. Defaulting to 1 ControlNet Unit for now.

To work around not having control_types, I'm re-creating the format and putting everything in the "All" category. It's messy, but it populates the dropdowns.

I don't have my ControlNet models linked yet, but I've pushed the change. Give it a test and see if it works for you.

**Comment by Hellrunner2k** [comment] 2024-03-24 01:59
aye, sir... promptly

**Comment by Hellrunner2k** [comment] 2024-03-24 07:59
yeeeii :D 
![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/16692344/3c061390-2916-4d17-aa63-4101ea9c3559)

Good stuff, thank you so much ^^

preprocessor shenanigans still persists... but i can live without them for now :D

KeyError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Sun Mar 24 08:57:53 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py in <lambda>()
  138         self.preprocessor_select.setMaxVisibleItems(5) # Suppose to limit the number of visible options
  139         # self.preprocessor_select.currentIndexChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText())) # ... This steps through EVERY index in between
  140         self.preprocessor_select.currentTextChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText()))
  141         control_type_row.layout().addRow('Preprocessor', self.preprocessor_select)
  142 
self = <cyanic.extension_widgets.controlnet.ControlNetUnit object>
self.preprocessor_select = <PyQt5.QtWidgets.QComboBox object>
self.preprocessor_select.currentTextChanged = <bound PYQT_SIGNAL currentTextChanged of QComboBox object>
self.preprocessor_select.currentTextChanged.connect = <built-in method connect of PyQt5.QtCore.pyqtBoundSignal object>
self.set_preprocessor_settings = <bound method ControlNetUnit.set_preprocessor_se...ension_widgets.controlnet.ControlNetUnit object>>
self.preprocessor_select.currentText = <built-in method currentText of QComboBox object>

 C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py in set_preprocessor_settings(self=<cyanic.extension_widgets.controlnet.ControlNetUnit object>, preprocessor_name='canny')
  398         self.preprocessor = preprocessor_name
  399 
  400         details = self.cnapi.module_details[preprocessor_name]
  401         self.model_select.setHidden(details['model_free'])
  402 
details undefined
self = <cyanic.extension_widgets.controlnet.ControlNetUnit object>
self.cnapi = <cyanic.extension_widgets.controlnet.ControlNetAPI object>
self.cnapi.module_details = {}
preprocessor_name = 'canny'
KeyError: 'canny'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('canny',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py", line 140, in <lambda>
    self.preprocessor_select.currentTextChanged.connect(lambda: self.set_preprocessor_settings(self.preprocessor_select.currentText()))
  File "C:\Users\DicktatorF\AppData\Roaming\krita\pykrita\cyanic\extension_widgets\controlnet.py", line 400, in set_preprocessor_settings
    details = self.cnapi.module_details[preprocessor_name]
KeyError: 'canny'

![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/16692344/6e93662b-9e8c-4688-9c67-9034f251ad55)

**Comment by DrCyanide** [comment] 2024-04-15 05:35
Please try pulling the latest version of the plugin, I believe this is fixed now. I've disabled some preprocessor options that Forge's API doesn't currently support, and I think it's stable now.

**Closed as completed** 2024-04-15 16:50 UTC
